### ISSUE TITLE
ApollosPlayerContainer & Device Notch

### ISSUE THREAD

**Issue by MatthewKyle22** [ApollosProject/apollos-templates#395]
The Apollos Player currently uses the screen portion above a device notch which cuts off content from the videos played in portrait mode. (See attached screen shot)
You might be able to use React Natives StatusBar component to check the height. Ex. StatusBar.currentHeight and then use the value given back to dynamically add margin to the top of the  video player to fix the issue?
![Screen Shot 2021-06-15 at 10 15 08 AM](https://user-images.githubusercontent.com/11671126/122078954-96a9ec00-cdc2-11eb-9d60-518dba2011e6.png)

**Comment by camrun91** [comment]
This has been fixed in Core.
