### ISSUE TITLE
Follow and other notifications Crash the app

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-templates#421]
so there are two issues here one is in the providers.js file it is trying to split the URL on the string "app-link" and that is throwing an error then when the follow requested Notifications are sent I get an error saying `payload {"name":"Tabs?screen=Connect"} was not handled by any navigator."` any guidance would be appreciated.

**Comment by redreceipt** [comment]
How can I reproduce?

**Comment by camrun91** [comment]
> How can I reproduce?

For me all I had to do was run the app and then in safari try and navigate to a link as I would expect the app to open such as `crossings://AppStackNavigator/Connect` in the simulator. Also on our app we can reproduce this by clicking the notification that comes across when I request to follow someone.

**Comment by camrun91** [comment]
@redreceipt to clarify this either I missed something in the link set up or the templates repo following SMS push notifications are broken.

**Comment by camrun91** [comment]
@redreceipt it looks like the follow issue is here https://github.com/ApollosProject/apollos-apps/blob/3ea9d4b1de4d5dd01f3b3caec4256e57e8ab8f84/packages/apollos-data-connector-postgres/src/follows/dataSource.js#L118 

that line is not putting in the expected "app-link" before the path from here. https://github.com/ApollosProject/apollos-templates/blob/adf12a15d3ebeee335a9fed7dacb77fc6ab66090/apolloschurchapp/src/Providers.js#L23

**Comment by redreceipt** [comment]
The core template is expecting deep links in form `host://app-link/nav/Connect`

**Comment by camrun91** [comment]
> The core template is expecting deep links in form `host://app-link/nav/Connect`

I have this stuff working the issue I am having is that in core the link that gets created when a follow request comes through is not in this format. 

https://github.com/ApollosProject/apollos-apps/blob/3ea9d4b1de4d5dd01f3b3caec4256e57e8ab8f84/packages/apollos-data-connector-postgres/src/follows/dataSource.js#L118

I think you can reproduce by running the template repo and generating a following request link.

**Comment by redreceipt** [comment]
Oh yea that looks wrong. Good find. I’ll test tomorrow.

**Comment by camrun91** [comment]
@redreceipt just yesterday I got a push notification from our app that someone had prayed for me. Clicking it crashed the app as well. This is the only place I see the notification being created but there is no route or anything unless I am missing something? 
https://github.com/ApollosProject/apollos-apps/blob/792a2b78832aa8c6cb5fb9f90eab733c76bbaad1/packages/apollos-data-connector-rock/src/prayer-request/data-source.js#L122

**Comment by redreceipt** [comment]
Can you create a separate more specific issue for this “prayed for notifications crash the app” and reference this line for us

**Comment by camrun91** [comment]
yes I will
