### ISSUE TITLE
Feature: iPad support

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-templates#436]
I have confirmed that iPad support is almost good from the templates repo. However the only issue I am seeing is that the home feed is getting split into two columns. The pictures below are what happens in the core repo. The home feed is split but the connect page is not. 
![Screen Shot 2021-07-21 at 12 51 29 PM](https://user-images.githubusercontent.com/16566029/126537502-2cad295f-d88c-43f3-81d9-3601f7e81451.png)
![Screen Shot 2021-07-21 at 12 55 30 PM](https://user-images.githubusercontent.com/16566029/126537516-3882e876-585f-40ae-8695-d6a33eedf882.png)

**Comment by camrun91** [comment]
As I told @redreceipt it appears that on iPad on the home feed (at least) the feature feed flatlist's numcolumns prop is getting set to 2 instead of one.

**Comment by camrun91** [comment]
@redreceipt I figured out the issue. it has to do with the break points and the media queries. https://github.com/ApollosProject/apollos-apps/blob/10749d804a9322ab19c4660cf30819d51399df00/packages/apollos-ui-kit/src/FeedView/index.js#L145 

Changing that to lg instead of md made it work. we were able to get around this by overriding the breakpoints in our theme file.

**Comment by redreceipt** [comment]
@camrun91 has this been completed?

**Comment by camrun91** [comment]
I think it has been completed with recent updates.
