### ISSUE TITLE
multiple calendar support

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-templates#441]
### Discussed in https://github.com/ApollosProject/apollos-templates/discussions/438

<div type='discussions-op-text'>

<sup>Originally posted by **camrun91** July 25, 2021</sup>
I am looking at adding Events to our search. However, the Apollos Api for Rock only pulls from one calendar. We use a few different calendars currently. I want to eventually move to a single calendar but if we could add support for multiple calendars that would be good. </div>

**Comment by camrun91** [comment]
@redreceipt fyi I have this working currently in our API it is pulling the calendar ID's from the config file and then just looping over them as I can't find a way in Rock to get multiple calendars in one query. I can look into a PR for core but I feel it probably is not the best solution.

**Comment by redreceipt** [comment]
Yea I think that’s the snag we’ve hit in the past too. And yea I agree, we’d want something a little more elegant to add support.

**Comment by redreceipt** [comment]
we have no plans to support Rock events, they'll be content items in the DB moving forward
